#!/usr/bin/env bash
# sets up nginX on web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw default allow
sudo ufw allow 'Nginx HTTP'
echo "y" | sudo ufw enable
echo "Holberton School for the win!" > /var/www/html/index.html
