#!/bin/bash
#prints holberton school 10 times but 4th and 8th are changed
i=1
while [ $i -ne 11 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i+1))
done
