#!/usr/bin/env bash
# installs ufw firewall, allows port 22, 80, and 443
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
