#!/usr/bin/env bash
# changes IP adresses in the hosts file
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
