#!/usr/bin/env bash
# advanced task
sudo chmod 644 /etc/nginx/nginx.conf
sudo echo "user nginx" | sudo tee -a /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
